CREATE TABLE categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(60)                 NOT NULL UNIQUE,
    position   INTEGER                     NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE dishes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT                      NOT NULL REFERENCES categories (id),
    name        VARCHAR(100)                NOT NULL,
    description VARCHAR(500),
    price       NUMERIC(10, 2)              NOT NULL CHECK (price >= 0),
    available   BOOLEAN                     NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_dishes_category ON dishes (category_id);

CREATE TABLE dish_allergens (
    dish_id  BIGINT      NOT NULL REFERENCES dishes (id) ON DELETE CASCADE,
    allergen VARCHAR(30) NOT NULL,
    PRIMARY KEY (dish_id, allergen)
);

CREATE TABLE restaurant_tables (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(40)                 NOT NULL UNIQUE,
    token      VARCHAR(64)                 NOT NULL UNIQUE,
    active     BOOLEAN                     NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id   BIGINT                      NOT NULL REFERENCES restaurant_tables (id),
    status     VARCHAR(20)                 NOT NULL,
    notes      VARCHAR(500),
    total      NUMERIC(10, 2)              NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_table ON orders (table_id);

CREATE TABLE order_lines (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    dish_id    BIGINT         REFERENCES dishes (id) ON DELETE SET NULL,
    dish_name  VARCHAR(100)   NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    quantity   INTEGER        NOT NULL CHECK (quantity > 0),
    notes      VARCHAR(200)
);
CREATE INDEX idx_order_lines_order ON order_lines (order_id);

CREATE TABLE app_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)                 NOT NULL UNIQUE,
    password_hash VARCHAR(100)                NOT NULL,
    role          VARCHAR(20)                 NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
